spring:
  cloud:
    # 网关配置
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: strr-auth
          uri: lb://strr-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: strr-system
          uri: lb://strr-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 资源模块
        - id: strr-resource
          uri: lb://strr-resource
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
        # 数据模块
        - id: strr-data
          uri: lb://strr-data
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1