spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.system.url}
    username: ${datasource.system.username}
    password: ${datasource.system.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/data/*.xml
  crud-mapper-package: com.strr.data.mapper