version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - dev
  redis:
    image: redis:6.2.12
    container_name: redis-server
    ports:
      - 6379:6379
    command:
      - --requirepass password
    networks:
      - dev
  nacos:
    build:
      context: ../strr-visual/strr-nacos
    image: strr-nacos:1.0
    container_name: strr-nacos
    ports:
      - 8848:8848
      - 9848:9848
    networks:
      - dev
  system:
    build:
      context: ../strr-module/strr-system
    image: strr-system:1.0
    container_name: strr-system
    networks:
      - dev
  auth:
    build:
      context: ../strr-auth
    image: strr-auth:1.0
    container_name: strr-auth
    networks:
      - dev
  data:
    build:
      context: ../strr-module/strr-data
    image: strr-data:1.0
    container_name: strr-data
    networks:
      - dev
  resource:
    build:
      context: ../strr-module/strr-resource
    image: strr-resource:1.0
    container_name: strr-resource
    networks:
      - dev
  gateway:
    build:
      context: ../strr-gateway
    image: strr-gateway:1.0
    container_name: strr-gateway
    networks:
      - dev
#  admin-ui:
#    build:
#      context: ../config/ui
#    image: strr-admin-ui:1.0
#    container_name: strr-admin-ui
#    ports:
#      - 8000:8000
#    networks:
#      - dev

networks:
  dev:
    name: dev